version: '3.8'

services:

  inventorydb:
    container_name: inventorydb
    image: mysql
    ports:
      - "3307:3307"
    environment:
      - MYSQL_ROOT_USERNAME=root
      - MYSQL_ROOT_PASSWORD=1598753
      - MYSQL_TCP_PORT=3307
      - VIRTUAL_PORT=3307
    volumes:
      - inventorydb_data:/data/db

volumes:
  inventorydb_data:

networks:
  monitor-net:
    driver: bridge