version: '3.8'

services:
  kafkadbemail:
    image: bashj79/kafka-kraft
    ports:
      - "9092:9092"
    volumes:
      - kafkadbemail_data:/opt/kafka/kafka-logs

  inventorydbemail:
    container_name: inventorydb-turkcell
    image: mysql
    ports:
      - "3308:3308"
    environment:
      - MYSQL_ROOT_USERNAME=root
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_TCP_PORT=3308
      - VIRTUAL_PORT=3308
    volumes:
      - inventorydbemail_data:/data/db

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-turkcell
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    command: start-dev
    volumes:
      - .:/opt/jboss/keycloak/imports

volumes:
  kafkadbemail_data:
  inventorydbemail_data:

networks:
  monitor-net:
    driver: bridge