version: '3.8'

services:
  kafkadbemail:
    image: bashj79/kafka-kraft
    ports:
      - "9092:9092"
    volumes:
      - kafkadbemail_data:/opt/kafka/kafka-logs

  inventorydb:
    container_name: inventorydb
    image: mysql
    ports:
      - "3307:3307"
    environment:
      - MYSQL_ROOT_USERNAME=root
      - MYSQL_ROOT_PASSWORD=1598753
      - MYSQL_TCP_PORT=3307
      - VIRTUAL_PORT=3307
    volumes:
      - inventorydb_data:/data/db

  verificationdb:
    container_name: verificationdb
    image: mysql
    ports:
      - "3308:3308"
    environment:
      - MYSQL_ROOT_USERNAME=root
      - MYSQL_ROOT_PASSWORD=1598753
      - MYSQL_TCP_PORT=3308
      - VIRTUAL_PORT=3308
    volumes:
      - verificationdb_data:/data/db


  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-turkcell
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    command: start-dev
    volumes:
      - .:/opt/jboss/keycloak/imports

volumes:
  kafkadbemail_data:
  inventorydb_data:
  verificationdb_data:

networks:
  monitor-net:
    driver: bridge