version: '3.8'

services:
  kafkadbemail:
    image: bashj79/kafka-kraft
    ports:
      - "9092:9092"
    volumes:
      - kafkadbemail_data:/opt/kafka/kafka-logs

  inventorydbemail2:
    container_name: inventorydb-email
    image: mysql
    ports:
      - "3307:3307"
    environment:
      - MYSQL_ROOT_PASSWORD=1598753
      - MYSQL_TCP_PORT=3307
      - VIRTUAL_PORT=3307
    volumes:
      - inventorydbemail2_data:/data/db

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-turkcell
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    command: start-dev
    volumes:
      - .:/opt/jboss/keycloak/imports

volumes:
  kafkadbemail_data:
  inventorydbemail2_data:

networks:
  monitor-net:
    driver: bridge