spring:
  application:
    name: inventory-service

  datasource:
    username: root
    password: 1598753
    url: jdbc:mysql://localhost:3307/demodb?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    username: barisyurdakul.by@gmail.com
    properties:
      mail:
        smtp:
          starttls:
            required: 'true'
            enable: 'true'
          writetimeout: '5000'
          timeout: '5000'
          auth: 'true'
          connectiontimeout: '5000'
    port: '587'
    password: 18083543574
logging:
  level:
    com:
      springsecurity:
        demo: DEBUG
    org:
      hibernate: WARN
      springframework: WARN

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}}
    prefer-ip-address: true
server:
  port: 0

