spring:
  application:
    name: inventory-service

  datasource:
    username: root
    password: '12345'
    url: jdbc:mysql://localhost:3306/inventory-mysql
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
server:
  port: 0

